"""Paths to the used programms."""

import os.path

MLONMCU_HOME = os.path.expandvars("$MLONMCU_HOME")

LLVM_PATH = "/home/cecil/Documents/llvm-project/build"
ETISS_PATH = "/home/cecil/Documents/etissVK"
ETISS_RUN_HELPER = ETISS_PATH + "/build/installed/bin/run_helper.sh"
MLONMCU_PATH = "/home/cecil/Documents/mlonmcu"

# Currently not needed/used
VENV_NAME = "venv"
M2_ISA_R_PATH = "~/Documents/M2-ISA-R"
SEAL5_PATH = "~/Documents/seal5"

EMBENCH = [
    "edn",
    "crc32",
    "wikisort",
    "slre",
    "qrduino",
    "minver",
    "picojpeg",
    "tarfind",
    "st",
    "nsichneu",
    "statemate",
    "primecount",
    "md5sum",
    "nettle-sha256",
    "nettle-aes",
    "ud",
    "matmult-int",
    "aha-mont64",
    "huffbench",
    "cubic",
    "nbody",
    "sglib-combined",
]
"""Individual embench Benchmarks"""

TACLEBENCH = [
    "app/powerwindow",
    "app/lift",
    "sequential/epic",
    "sequential/huff_dec",
    "sequential/fmref",
    "sequential/h264_dec",
    "sequential/dijkstra",
    "sequential/adpcm_dec",
    "sequential/adpcm_enc",
    "sequential/gsm_dec",
    "sequential/rijndael_dec",
    "sequential/g723_enc",
    "sequential/huff_enc",
    "sequential/statemate",
    "sequential/susan",
    "sequential/gsm_enc",
    "sequential/ndes",
    "sequential/audiobeam",
    "sequential/rijndael_enc",
    "sequential/cjpeg_transupp",
    "sequential/ammunition",
    "sequential/mpeg2",
    "sequential/anagram",
    "sequential/cjpeg_wrbmp",
    "sequential/petrinet",
    "test/test3",
    "test/cover",
    "test/duff",
    "kernel/deg2rad",
    "kernel/matrix1",
    "kernel/binarysearch",
    "kernel/pm",
    "kernel/sha",
    "kernel/filterbank",
    "kernel/md5",
    "kernel/fir2dim",
    "kernel/fft",
    "kernel/minver",
    "kernel/lms",
    "kernel/bitcount",
    "kernel/st",
    "kernel/bsort",
    "kernel/bitonic",
    "kernel/iir",
    "kernel/prime",
    "kernel/jfdctint",
    "kernel/recursion",
    "kernel/complex_updates",
    "kernel/cosf",
    "kernel/insertsort",
    "kernel/fac",
    "kernel/rad2deg",
    "kernel/isqrt",
    "kernel/cubic",
    "kernel/ludcmp",
    "kernel/quicksort",
    "kernel/countnegative",
]
"""
Individual benchmarks in "taclebench", 
Most benchmarks see no improvements
Most promising = ["sequential/epic", "sequential/susan"]
"""

BENCHMARKS = ["coremark", "dhrystone", "mathis", "taclebench", "embench", *EMBENCH]

EXTENSIONS = [
    "+xseal5testalucvabs16",
    "+xseal5testalucvabs32",
    "+xseal5testalucvabs8",
    "+xseal5testalucvaddnrsi16",
    "+xseal5testalucvaddnrsi32",
    "+xseal5testalucvaddnrui16",
    "+xseal5testalucvaddnrui32",
    "+xseal5testalucvaddns",
    "+xseal5testalucvaddnu",
    "+xseal5testalucvaddrnrsi16",
    "+xseal5testalucvaddrnrsi32",
    "+xseal5testalucvaddrnrui16",
    "+xseal5testalucvaddrnrui32",
    "+xseal5testalucvaddrns",
    "+xseal5testalucvaddrnu",
    "+xseal5testalucvextbs",
    "+xseal5testalucvextbz",
    "+xseal5testalucvexths",
    "+xseal5testalucvexthz",
    "+xseal5testalucvmaxi1216",
    "+xseal5testalucvmaxi1232",
    "+xseal5testalucvmaxi516",
    "+xseal5testalucvmaxi532",
    "+xseal5testalucvmaxs16",
    "+xseal5testalucvmaxs32",
    "+xseal5testalucvmaxs8",
    "+xseal5testalucvmaxu16",
    "+xseal5testalucvmaxu32",
    "+xseal5testalucvmaxu8",
    "+xseal5testalucvmini1216",
    "+xseal5testalucvmini1232",
    "+xseal5testalucvmini516",
    "+xseal5testalucvmini532",
    "+xseal5testalucvmins16",
    "+xseal5testalucvmins32",
    "+xseal5testalucvmins8",
    "+xseal5testalucvminu16",
    "+xseal5testalucvminu32",
    "+xseal5testalucvminu8",
    "+xseal5testalucvsletsi16",
    "+xseal5testalucvsletsi32",
    "+xseal5testalucvsletui16",
    "+xseal5testalucvsletui32",
    "+xseal5testalucvsubnrsi16",
    "+xseal5testalucvsubnrsi32",
    "+xseal5testalucvsubnrui16",
    "+xseal5testalucvsubnrui32",
    "+xseal5testalucvsubns",
    "+xseal5testalucvsubnu",
    "+xseal5testalucvsubrnrsi16",
    "+xseal5testalucvsubrnrsi32",
    "+xseal5testalucvsubrnrui16",
    "+xseal5testalucvsubrnrui32",
    "+xseal5testalucvsubrns",
    "+xseal5testalucvsubrnu",
    "+xseal5testmaccvmachhns",
    "+xseal5testmaccvmachhnu",
    "+xseal5testmaccvmachhrns",
    "+xseal5testmaccvmachhrnu",
    "+xseal5testmaccvmacns",
    "+xseal5testmaccvmacnu",
    "+xseal5testmaccvmacrns",
    "+xseal5testmaccvmacrnu",
    "+xseal5testmaccvmacsi16",
    "+xseal5testmaccvmacsi32",
    "+xseal5testmaccvmacui16",
    "+xseal5testmaccvmacui32",
    "+xseal5testmaccvmsusi16",
    "+xseal5testmaccvmsusi32",
    "+xseal5testmaccvmsuui16",
    "+xseal5testmaccvmsuui32",
    "+xseal5testmaccvmulhhns",
    "+xseal5testmaccvmulhhnu",
    "+xseal5testmaccvmulhhrns",
    "+xseal5testmaccvmulhhrnu",
    "+xseal5testmaccvmulns",
    "+xseal5testmaccvmulnu",
    "+xseal5testmaccvmulrns",
    "+xseal5testmaccvmulrnu",
    "+grp32v",
]
